name: my first ci
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello world!"
      - name: print goodbye
        run: echo "done - bye"
